/**
 * 2026-09-09 — live /about-chris/ overlay (hosting/about-chris/index.html).
 *
 * PR #17 brought the live hand-authored About Chris page under version control
 * and hand-mirrored the homepage header CSS into it. Chris's full lock
 * (docs/LOCKED_SITECHROME.md) requires the FULL homepage footer too, which a
 * hand-mirrored page cannot carry without duplicating chrome. The overlay is
 * therefore the Next export of src/app/about-chris/page.tsx, regenerated by
 * scripts/export-about-chris-overlay.sh together with the _next/ assets it
 * needs (export/about-chris-sitechrome-<date>.zip). This suite locks that.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { LAUNCH_DEMO_HREF } from "@/lib/site";

function src(relative: string) {
  return readFileSync(resolve(process.cwd(), relative), "utf8");
}

const NAV_CLASSES =
  'class="mx-auto flex h-16 w-full max-w-[1240px] items-center justify-between gap-4 px-5 sm:px-8"';

function count(haystack: string, needle: string) {
  return haystack.split(needle).length - 1;
}

describe("2026-09-09 live /about-chris/ overlay is the Next export with the shared SiteChrome", () => {
  const page = src("hosting/about-chris/index.html");
  const header = src("src/components/SiteHeader.tsx");

  it("is the static export, not a hand-authored document", () => {
    expect(page).toMatch(/<link rel="stylesheet" href="\/_next\/static\/chunks\/[^"]+\.css"/);
    expect(page).toContain('<link rel="canonical" href="https://teamulate.ca/about-chris/"/>');
    expect(page).not.toContain("SiteChrome header"); // PR #17's hand-mirrored CSS marker
    expect(page).not.toMatch(/max-width:\s*1100px|class="wrap"|class="draft-banner"|tm-mobile-nav/);
    expect(page).not.toMatch(/preview only|noindex/i);
  });

  it("carries exactly one shared header with the SiteHeader container and About ▾ trigger", () => {
    expect(count(page, "<header")).toBe(1);
    expect(page).toContain(NAV_CLASSES);
    expect(header).toContain(NAV_CLASSES.replace('class="', 'className="'));
    expect(page).toContain('class="hidden items-center gap-1 lg:flex"');
    expect(page).toContain('class="hidden items-center gap-3 lg:flex"');
    // About is the current section on this page → brand; still plain text + chevron (no box).
    expect(page).toContain(
      'class="flex items-center gap-1 rounded-md px-3 py-2 text-sm font-medium hover:text-brand text-brand">About<span aria-hidden="true" class="text-[10px]">▾</span></button>',
    );
    for (const label of [">How it works</a>", ">Pricing</a>", ">Blog</a>", ">Demo</a>", ">Login</a>", ">Launch Demo</a>", ">Menu</button>"]) {
      expect(page).toContain(label);
    }
    expect(page).not.toContain('href="/team/">Team</a>');
  });

  it("Launch Demo and Demo target the filled demo as full-document anchors; Login → /app/", () => {
    expect(page).toContain(`href="${LAUNCH_DEMO_HREF}"`);
    expect(page).not.toContain('href="/demo/dashboard/"');
    expect(page).toContain('href="/app/"');
  });

  it("carries exactly one FULL homepage footer (not a socials-only bar)", () => {
    expect(count(page, "<footer")).toBe(1);
    expect(page).toContain('<footer class="border-t border-line bg-surface-muted">');
    expect(page).toContain("A full marketing department. Without building one.");
    expect(page).toContain("Chris Momchilov is the founder above Teamulate.");
    expect(count(page, 'aria-label="Teamulate on social"')).toBe(1);
    expect(page).toContain('data-teamulate-social="2"');
    for (const group of ["Footer Product", "Footer Guides", "Footer Plans", "Footer Company"]) {
      expect(page).toContain(`aria-label="${group}"`);
    }
    expect(page).toContain("Stay in the loop");
    expect(page).toContain('id="newsletter-email"');
    expect(page).toContain('href="/privacy/"');
    expect(page).toContain('href="/terms/"');
    expect(page).toContain("Teamulate · Autonomous marketing department");
  });

  it("does not touch the page body: hero, tiles, quote and CTAs are the locked copy", () => {
    expect(page).toContain("Chris Momchilov</h1>");
    expect(page).toContain("12 years in B2B marketing. Builder of a live multi-agent AI marketing system");
    expect(page).toContain(">12<");
    expect(page).toContain(">11<");
    expect(page).toContain("28×");
    expect(page).toContain("I don’t just use AI — I built a live multi-agent marketing system and run it with human oversight.");
    expect(page).toContain('href="/request-demo/">See the department');
    expect(page).toContain('href="https://www.youtube.com/@SingularityDrive"');
    expect(page).toContain('src="/about-chris/hero-card-4x3.webp"');
    expect(page).toContain('src="/about-chris/ai-systems-diagram.svg"');
    expect(page).not.toMatch(/10\+/);
  });

  it("Singularity Drive card embeds the channel trailer (Y9AdO6d9x5U) as a 16:9 click-to-play iframe, keeping the CTA", () => {
    const source = src("src/app/about-chris/page.tsx");
    expect(source).toContain('const SINGULARITY_DRIVE_TRAILER_ID = "Y9AdO6d9x5U";');
    expect(page).toContain('src="https://www.youtube-nocookie.com/embed/Y9AdO6d9x5U"');
    expect(page).toContain('title="Singularity Drive Trailer"');
    expect(count(page, "<iframe")).toBe(1);
    expect(page).toMatch(/<iframe[^>]*class="absolute inset-0 h-full w-full"/);
    expect(page).toMatch(/<div class="relative aspect-video w-full"><iframe/);
    expect(page).not.toMatch(/autoplay/i);
    // The gradient play-button placeholder is gone; the text block + CTA remain.
    expect(page).not.toContain('aria-label="Open Singularity Drive on YouTube"');
    expect(page).not.toContain(">YouTube channel<");
    expect(page).toContain(">On YouTube<");
    expect(page).toContain("Singularity Drive</h2>");
    expect(page).toMatch(/href="https:\/\/www\.youtube\.com\/@SingularityDrive"[^>]*>Watch on YouTube/);
  });

  it("ships with a deploy zip that contains every _next/ and about-chris/ asset the page references", () => {
    const zips = readdirSync(resolve(process.cwd(), "export")).filter((f) => /^about-chris-sitechrome-\d{4}-\d{2}-\d{2}\.zip$/.test(f));
    expect(zips.length).toBeGreaterThan(0);
    const latest = zips.sort().at(-1)!;
    // Zip entries store their file names as plain bytes, so a byte search is a reliable membership check.
    const zip = readFileSync(resolve(process.cwd(), "export", latest)).toString("latin1");
    const assets = Array.from(page.matchAll(/(?:href|src)="\/(_next\/[^"]+|about-chris\/[^"]+)"/g)).map((m) => m[1]);
    expect(assets.length).toBeGreaterThan(5);
    const missing = Array.from(new Set(assets)).filter((asset) => !zip.includes(asset));
    expect(missing, `${latest} is missing assets referenced by hosting/about-chris/index.html`).toEqual([]);
    expect(zip).toContain("about-chris/index.html");
    expect(existsSync(resolve(process.cwd(), "scripts/export-about-chris-overlay.sh"))).toBe(true);
  });
});

describe("2026-09-09 /js/about-nav.js dropdown trigger", () => {
  const js = src("hosting/js/about-nav.js");

  it("renders About as text + chevron with inline resets so no page can draw a UA button box", () => {
    expect(js).toContain('var VER = "3";');
    expect(js).toContain('btn.style.background = "transparent";');
    expect(js).toContain('btn.style.border = "0";');
    expect(js).toContain('btn.style.font = "inherit";');
    expect(js).toContain('btn.style.padding = "8px 12px";');
    expect(js).toContain("'About <span aria-hidden=\"true\" style=\"font-size:10px\">▾</span>'");
    expect(js).toContain("styleTrigger(btn);");
  });

  it("keeps the same children and highlights About when Chris or The Team is current", () => {
    expect(js).toContain('chris.href = "/about-chris/";');
    expect(js).toContain('chris.textContent = "Chris";');
    expect(js).toContain('team.href = "/team/";');
    expect(js).toContain('team.textContent = "The Team";');
    expect(js).toContain('(chrisActive || teamActive ? "text-brand" : "text-ink")');
  });

  it("is a no-op on pages exported from this repo (About ▾ is already in the markup)", () => {
    // v3 only replaces a top-level <a href="/team/">Team</a>; SiteHeader renders none.
    expect(js).toContain('cluster.querySelectorAll(\'a[href="/team/"]\')');
    expect(js).toMatch(/if \(t === "Team"\)/);
    expect(src("hosting/about-chris/index.html")).not.toContain('href="/team/">Team</a>');
  });
});
