import type { AgentType } from "@/domain/enums";

export type AgentProfile = {
  slug: string;
  name: string;
  role: string;
  type: AgentType;
  mission: string;
  responsibilities: string[];
  typicalInputs: string[];
  typicalOutputs: string[];
  worksCloselyWith: string[];
  toolCategories: string[];
  kpis: string[];
  autonomousActions: string[];
  approvalRequiredActions: string[];
  emailFormat: string;
  accent: string;
};

/** 11-agent roster per spec §12.5. 1 head + 8 execution specialists + 2 independent assurance agents. */
export const AGENTS: AgentProfile[] = [
  {
    slug: "strategos",
    name: "Strategos",
    role: "Head of Marketing / Orchestrator",
    type: "orchestrator",
    mission: "Turn business goals into a prioritized, coordinated marketing operating plan.",
    responsibilities: [
      "Goal intake and prioritization",
      "Campaign briefs and delegation",
      "Cross-agent coordination and cadence",
      "Exception handling and escalation",
      "Executive summaries and decision packets",
    ],
    typicalInputs: ["Business goals", "Approved knowledge base", "Performance readouts", "Client requests"],
    typicalOutputs: ["Prioritized plan", "Campaign brief", "Decision packet", "Executive summary"],
    worksCloselyWith: ["All specialists", "Guardian", "Metric"],
    toolCategories: ["Planning", "Reporting", "Knowledge base"],
    kpis: ["Goal progress", "Plan reliability", "Approval turnaround supported"],
    autonomousActions: ["Prioritization", "Brief drafting", "Delegation", "Status reporting"],
    approvalRequiredActions: ["New strategy", "Goal changes", "Material budget shifts"],
    emailFormat: "strategos.yourcompany@teamulate.ca",
    accent: "var(--tm-blue-600)",
  },
  {
    slug: "scout",
    name: "Scout",
    role: "Intelligence & Product Marketing",
    type: "specialist",
    mission: "Keep the department grounded in validated market, competitor and audience intelligence.",
    responsibilities: [
      "Market and competitor research",
      "ICP validation and segmentation",
      "Positioning inputs and battlecards",
      "Win/loss and audience pain analysis",
    ],
    typicalInputs: ["Public sources", "Approved research scope", "CRM signals"],
    typicalOutputs: ["Research brief", "Competitor update", "ICP", "Positioning", "Battlecard"],
    worksCloselyWith: ["Strategos", "Wordsmith", "GrowthTrack"],
    toolCategories: ["Research", "Enrichment", "Knowledge base"],
    kpis: ["Evidence coverage", "Research acceptance rate"],
    autonomousActions: ["Monitoring", "Research synthesis", "Draft briefs"],
    approvalRequiredActions: ["Publishing competitive claims externally"],
    emailFormat: "scout.yourcompany@teamulate.ca",
    accent: "var(--tm-cyan-600)",
  },
  {
    slug: "wordsmith",
    name: "Wordsmith",
    role: "Content, Social & Community",
    type: "specialist",
    mission: "Produce clear, on-brand content that moves defined audiences to action.",
    responsibilities: [
      "Editorial planning",
      "Articles, newsletters and campaign copy",
      "Social content and community drafts",
      "Message consistency across channels",
    ],
    typicalInputs: ["Approved messaging", "Research briefs", "Brand voice guidelines"],
    typicalOutputs: ["Editorial plan", "Articles", "Social posts", "Newsletters", "Campaign copy"],
    worksCloselyWith: ["Scout", "Seeker", "Pixel", "Guardian"],
    toolCategories: ["CMS", "Social", "Editorial tools"],
    kpis: ["QA first-pass rate", "Content engagement"],
    autonomousActions: ["Drafting", "Revisions", "Internal reviews"],
    approvalRequiredActions: ["External publishing outside approved policy"],
    emailFormat: "wordsmith.yourcompany@teamulate.ca",
    accent: "var(--tm-purple-600)",
  },
  {
    slug: "seeker",
    name: "Seeker",
    role: "Search & GEO",
    type: "specialist",
    mission: "Grow qualified visibility in traditional and AI-assisted search.",
    responsibilities: [
      "Opportunity mapping",
      "SEO/GEO briefs and on-page recommendations",
      "Technical issue queues",
      "Internal-link planning",
    ],
    typicalInputs: ["Search console data", "Analytics", "Content inventory"],
    typicalOutputs: ["Opportunity map", "SEO/GEO brief", "Issue queue", "Internal-link plan"],
    worksCloselyWith: ["Wordsmith", "Flow", "Metric"],
    toolCategories: ["Search analytics", "Crawling", "CMS"],
    kpis: ["Qualified organic sessions", "Ranking visibility"],
    autonomousActions: ["Monitoring", "Diagnosis", "Brief creation"],
    approvalRequiredActions: ["Site-wide structural changes"],
    emailFormat: "seeker.yourcompany@teamulate.ca",
    accent: "var(--tm-green-600)",
  },
  {
    slug: "growthtrack",
    name: "GrowthTrack",
    role: "Demand Generation & Paid Growth",
    type: "specialist",
    mission: "Build and pace demand programs inside approved budgets and audiences.",
    responsibilities: [
      "Acquisition planning",
      "Audience setup",
      "Outbound drafts",
      "Budget pacing inside caps",
    ],
    typicalInputs: ["Campaign briefs", "Approved budgets", "Audience definitions"],
    typicalOutputs: ["Acquisition plan", "Audience setup", "Outbound draft", "Pacing actions"],
    worksCloselyWith: ["Strategos", "Pixel", "Nexus", "Metric"],
    toolCategories: ["Ad platforms", "Outbound", "CRM"],
    kpis: ["Qualified pipeline contribution", "Spend efficiency inside caps"],
    autonomousActions: ["Monitoring", "Bounded pacing inside policy"],
    approvalRequiredActions: ["Budget changes", "New audiences", "Campaign launches"],
    emailFormat: "growthtrack.yourcompany@teamulate.ca",
    accent: "var(--tm-orange-500)",
  },
  {
    slug: "pixel",
    name: "Pixel",
    role: "Creative Studio",
    type: "specialist",
    mission: "Produce consistent, conversion-oriented creative across formats.",
    responsibilities: [
      "Design packages",
      "Image and video variants",
      "Thumbnails and motion",
      "Captions and accessibility variants",
    ],
    typicalInputs: ["Briefs", "Brand assets", "Channel specs"],
    typicalOutputs: ["Design package", "Image/video variants", "Thumbnails", "Motion/captions"],
    worksCloselyWith: ["Wordsmith", "GrowthTrack", "Flow"],
    toolCategories: ["Design", "Video", "Asset management"],
    kpis: ["Creative acceptance rate", "Variant performance"],
    autonomousActions: ["Drafting", "Variant production"],
    approvalRequiredActions: ["Brand-system changes", "Sensitive imagery"],
    emailFormat: "pixel.yourcompany@teamulate.ca",
    accent: "var(--tm-pink-500)",
  },
  {
    slug: "flow",
    name: "Flow",
    role: "Web & CRO",
    type: "specialist",
    mission: "Turn traffic into qualified conversations through fast, clear web experiences.",
    responsibilities: [
      "Landing pages and forms",
      "CRO diagnosis",
      "Experiment configuration",
      "Web performance hygiene",
    ],
    typicalInputs: ["Campaign briefs", "Analytics", "Design packages"],
    typicalOutputs: ["Landing pages", "Forms", "CRO diagnosis", "Experiment configuration"],
    worksCloselyWith: ["Pixel", "Seeker", "Nexus", "Metric"],
    toolCategories: ["CMS", "Experimentation", "Analytics"],
    kpis: ["Conversion rate", "Experiment velocity"],
    autonomousActions: ["Draft builds", "Staging previews", "Diagnosis"],
    approvalRequiredActions: ["Production publishing per policy"],
    emailFormat: "flow.yourcompany@teamulate.ca",
    accent: "var(--tm-cyan-600)",
  },
  {
    slug: "socialite",
    name: "Socialite",
    role: "Lifecycle & Customer Marketing",
    type: "specialist",
    mission: "Move contacts through onboarding, nurture, retention and advocacy with consented communication.",
    responsibilities: [
      "Nurture and onboarding flows",
      "Retention and re-engagement",
      "Advocacy programs",
      "Preference-aware sending",
    ],
    typicalInputs: ["Lifecycle stages", "Consent state", "Campaign briefs"],
    typicalOutputs: ["Nurture flows", "Onboarding flows", "Retention flows", "Advocacy flows"],
    worksCloselyWith: ["Nexus", "Wordsmith", "Metric"],
    toolCategories: ["Email/lifecycle", "CRM"],
    kpis: ["Lifecycle progression", "Engagement quality"],
    autonomousActions: ["Drafting flows", "Monitoring"],
    approvalRequiredActions: ["New audience sends", "Batch size above policy"],
    emailFormat: "socialite.yourcompany@teamulate.ca",
    accent: "var(--tm-purple-600)",
  },
  {
    slug: "nexus",
    name: "Nexus",
    role: "Marketing Ops & CRM",
    type: "specialist",
    mission: "Keep data, routing and tracking dependable so every other function can trust the system.",
    responsibilities: [
      "CRM schema and hygiene",
      "Scoring and routing",
      "Integrations and tracking taxonomy",
      "Handoff reliability",
    ],
    typicalInputs: ["CRM data", "Integration scopes", "Measurement plan"],
    typicalOutputs: ["CRM schema", "Scoring", "Routing", "Tracking taxonomy"],
    worksCloselyWith: ["GrowthTrack", "Socialite", "Metric"],
    toolCategories: ["CRM", "Integration platform", "Analytics"],
    kpis: ["Data completeness", "Routing accuracy"],
    autonomousActions: ["Hygiene inside thresholds", "Diagnosis"],
    approvalRequiredActions: ["Bulk record changes", "Schema changes"],
    emailFormat: "nexus.yourcompany@teamulate.ca",
    accent: "var(--tm-blue-600)",
  },
  {
    slug: "metric",
    name: "Metric",
    role: "Analytics & Attribution",
    type: "assurance",
    mission: "Independently validate what actually happened, with confidence and limitations stated.",
    responsibilities: [
      "Validated dashboards",
      "Anomaly diagnosis",
      "Attribution with labelled models",
      "Experiment readouts",
    ],
    typicalInputs: ["Source data", "Metric dictionary", "Campaign context"],
    typicalOutputs: ["Validated dashboard", "Anomaly diagnosis", "Attribution", "Experiment readout"],
    worksCloselyWith: ["All agents", "Client stakeholders"],
    toolCategories: ["Analytics", "Attribution", "Data quality"],
    kpis: ["Data freshness", "Measurement coverage"],
    autonomousActions: ["Monitoring", "Validation", "Anomaly detection"],
    approvalRequiredActions: ["Metric definition changes"],
    emailFormat: "metric.yourcompany@teamulate.ca",
    accent: "var(--tm-green-600)",
  },
  {
    slug: "guardian",
    name: "Guardian",
    role: "QA, Governance & Brand Assurance",
    type: "assurance",
    mission: "Independently check brand, claims, facts, policy and release readiness before anything ships.",
    responsibilities: [
      "Pass / revise / block decisions",
      "Claim validation",
      "Release preflight",
      "Defect logs and escalation",
    ],
    typicalInputs: ["Draft outputs", "Claims registry", "Policies"],
    typicalOutputs: ["Pass/revise/block", "Claim validation", "Preflight", "Defect log", "Escalation"],
    worksCloselyWith: ["All agents", "Approvers"],
    toolCategories: ["QA", "Policy", "Knowledge base"],
    kpis: ["Defects caught pre-release", "False-pass rate"],
    autonomousActions: ["QA checks", "Blocking non-compliant releases"],
    approvalRequiredActions: ["Policy changes"],
    emailFormat: "guardian.yourcompany@teamulate.ca",
    accent: "var(--tm-red-600)",
  },
];

export const TEAM_STRUCTURE_SENTENCE = "1 head + 8 execution specialists + 2 independent assurance agents";
